name: Run in LXC
description: Run a script in an LXC container
author: wsdfhjxc

inputs:
  distr:
    description: "Distro's name (e.g. fedora)"
    required: true

  release:
    description: "Distro's version (e.g. 33)"
    required: true

  arch:
    description: "Distro's architecture (e.g. amd64)"
    required: true
    default: amd64

  run-script:
    description: Path to the script (e.g. scripts/test.sh)
    required: true

outputs:
  error-type:
    description: "Action error's type ('none', 'script' or 'internal')"

runs:
  using: node12
  main: main.js
