name: Run in LXC
description: Run a shell command or script in an LXC container
author: wsdfhjxc

inputs:
  distr:
    description: "Distro's name (e.g. fedora)"
    required: true

  release:
    description: "Distro's version (e.g. 33)"
    required: true

  arch:
    description: "Distro's architecture (e.g. amd64)"
    required: true
    default: amd64

  command:
    description: Command to run (e.g. ./scripts/test.sh)
    required: true

outputs:
  error-type:
    description: "Action error's type (script, internal)"

runs:
  using: node12
  main: main.js
