name: "Test: script"

on:
  workflow_dispatch:
    inputs:
        distr:
          description: "Distro's name"
          required: true
          default: fedora

        release:
          description: "Distro's version"
          required: true
          default: 33

jobs:
  test-script:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Run in LXC
        id: run-in-lxc
        uses: wsdfhjxc/run-in-lxc-action@v1
        with:
          distr: ${{ github.event.inputs.distr }}
          release: ${{ github.event.inputs.release }}
          command: |
            echo "Testing"
            ./scripts/test.sh

      - name: Validate error's type
        run: errorType=${{ steps.run-in-lxc.outputs.error-type }}

      - name: Validate test artifact
        run: cat test.txt
