name: Test - single

on:
  workflow_dispatch:

jobs:
  test-fedora-33:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: "Run in LXC (Fedora 33)"
        uses: wsdfhjxc/run-in-lxc-action@testing
        with:
          distr: fedora
          release: "33"
          arch: amd64
          run-script: scripts/test.sh

      - name: Validate test artifact
        run: cat test.txt
