name: Test - multi

on:
  workflow_dispatch:

jobs:
  test-fedora-33:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: "Run in LXC (Fedora 33)"
        uses: wsdfhjxc/run-in-lxc-action@testing
        with:
          distr: fedora
          release: "33"
          arch: amd64
          run-script: scripts/test.sh

      - name: Validate test artifact
        run: cat test.txt

  test-debian-sid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: "Run in LXC (Debian Sid)"
        uses: wsdfhjxc/run-in-lxc-action@testing
        with:
          distr: debian
          release: sid
          arch: amd64
          run-script: scripts/test.sh

      - name: Validate test artifact
        run: cat test.txt

  test-opensuse-tumbleweed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: "Run in LXC (openSUSE Tumbleweed)"
        uses: wsdfhjxc/run-in-lxc-action@testing
        with:
          distr: opensuse
          release: tumbleweed
          arch: amd64
          run-script: scripts/test.sh

      - name: Validate test artifact
        run: cat test.txt
