name: Test

on:
  workflow_dispatch:
    inputs:
        distr:
          description: "Distro's name"
          required: true
          default: fedora

        release:
          description: "Distro's version"
          required: true
          default: "33"

        arch:
          description: "Distro's architecture"
          required: true
          default: amd64

        runScript:
          description: Path to the script
          required: true
          default: scripts/test.sh

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Run in LXC
        uses: wsdfhjxc/run-in-lxc-action@testing
        with:
          distr: ${{ github.event.inputs.distr }}
          release: ${{ github.event.inputs.release }}
          arch: ${{ github.event.inputs.arch }}
          run-script: ${{ github.event.inputs.runScript }}

      - name: Validate test artifact
        run: cat test.txt
