name: Test

on:
  workflow_dispatch:
    inputs:
        distr:
          description: "Distro's name (e.g. fedora)"
          required: true
          default: fedora

        release:
          description: "Distro's version (e.g. 33)"
          required: true
          default: "33"

        arch:
          description: "Distro's architecture (e.g. amd64)"
          required: true
          default: amd64

        runScript:
          description: Path to the script (e.g. scripts/test.sh)
          required: true
          default: scripts/test.sh

jobs:
  test-fedora-33:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Run in LXC (Fedora 33)
        uses: wsdfhjxc/run-in-lxc-action@testing
        with:
          distr: ${{ github.event.inputs.distr }}
          release: ${{ github.event.inputs.release }}
          arch: ${{ github.event.inputs.arch }}
          run-script: ${{ github.event.inputs.runScript }}

      - name: Validate test artifact
        run: cat test.txt
